# In RStudio: open Assignment2.Rproj, run 01_setup.R, then source this file.
source("02_functions.R")
source("03_display.R")
dir.create("output", showWarnings = FALSE)
stocks <- load_stock_data("portfolio.txt", "2025-01-01", "2026-01-01")
display_stock_data(stocks)
results <- lapply(names(stocks), function(symbol) calculate_statistics(stocks[[symbol]], symbol, 20L))
names(results) <- names(stocks)
statistics <- display_statistics(results)
write.csv(statistics, "output/statistics.csv", row.names = FALSE)
for (symbol in names(results))
  write.csv(results[[symbol]]$data, file.path("output", paste0(symbol, "_data.csv")), row.names = FALSE)
failures <- attr(stocks, "failures")
write.csv(data.frame(Symbol = names(failures), Error = unname(failures)),
          "output/download_failures.csv", row.names = FALSE)
saveRDS(list(stocks = stocks, results = results), "output/analysis_objects.rds")
writeLines(capture.output(sessionInfo()), "output/session_info.txt")
plot_stock_data(results)
cat("\nAnalysis complete. Check output/ and download_failures.csv.\n")
